export const HEADER_GET_USERNAME_SUCCESS = 'HEADER_GET_USERNAME_SUCCESS';
export const HEADER_GET_USERNAME_FAILED = 'HEADER_GET_USERNAME_FAILED';
export const HEADER_GET_USERNAME_PENDING = 'HEADER_GET_USERNAME_PENDING';